.TH NAUTILUS-SENDTO 1 2006\-07\-18 "GNOME" "GNOME"
.SH NAME
nautilus\-sendto \- convenience application to send a file via email or instant messenger
.SH SYNOPSIS
.B nautilus-sendto
.RI [ OPTIONS " " | " " FILES... ]
.SH DESCRIPTION
Send FILE(s) via email or instant messenger.

A dialog window presents a choice of carrier application and recipient of the file(s).
Recipent names can be selected from a list or autocompleted. The selected application
is then opened with the file(s) and recipient ready for transfer.

The application is intented to integrate with nautilus and is
written for the GNOME graphical desktop.
.SH OPTIONS
.TP
.B \-?,  \-\-help
Show a help message listing all the options and their meanings.
.SH AUTHOR
Written by Roberto Majadas <roberto.majadas@openshine.com>
.PP
This manual page was originally written by Oystein Gisnas for the
Debian system.
.\" Copyright 2006 Oystein Gisnas
.\" You may copy this manual page under the terms of the version 2 of
.\" the GNU General Public License.
